name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v6
    - name: timestamp correction
      run:  ./utils/time-correct
    - name: configure
      run: ./configure
    - name: make
      run: make -j1
    - name: make check
      run: make check
  windows-build:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install mingw
        run: choco install mingw
    - name: timestamp correction
      run:  ./utils/time-correct
    - name: configure
      run: ./configure
    - name: make
      run: make -j1
    - name: make check
      run: make check
