name: C/C++ CI

on: [push, pull-request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v6
    - name: timestamp correction
      run:  ./utils/time-correct
    - name: configure
      run: ./configure
    - name: make
      run: make -j1
    - name: make check
      run: make check
#    - name: make distcheck
#      run: make distcheck
