name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - name: timestamp correction
        run:  ./utils/time-correct
      - name: configure
        run: ./configure
      - name: make
        run: make -j1
      - name: make check
        run: make check
  r7rs-tests:
    name: ${{ matrix.os }}-r7rs-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - name: timestamp correction
        run:  ./utils/time-correct
      - name: configure
        run: ./configure
      - name: make
        run: make -j1
      - name: make check
        run: make check
      - name: make install
        run: sudo make install
      - name: Clone tests
        run: git clone https://github.com/ashinn/chibi-scheme.git --depth=1 
      - name: Use (srfi 64) for tests
        run: sed -i 's/(chibi tests)/(srfi 64)/' chibi-scheme/tests/r7rs-tests.scm
      - name: Run r7rs-tests
        run: stklos chibi-scheme/tests/r7rs-tests.scm
